### ISSUE TITLE
内容中的<br>不会转换成换行

### ISSUE THREAD

**Issue by ddaodan** [gnuf0rce/rss-helper#14]
最新版本，所有的推送都没有换行，rss源里是用\<br>换行的

**Comment by cssxsh** [comment]
提交 issue 的时候请给 **具体的版本号**，还有请提供 rss源 以供测试

**Comment by ddaodan** [comment]
> 提交 issue 的时候请给 **具体的版本号**，还有请提供 rss源 以供测试

版本号1.1.0
rss源 [https://rsshub.app/twitter/user/norioo_](https://rsshub.app/twitter/user/norioo_)

**Comment by cssxsh** [comment]
with https://github.com/gnuf0rce/rss-helper/releases/tag/v1.1.1
