### ISSUE TITLE
不记录毫秒位, 导致历史记录异常

### ISSUE THREAD

**Issue by Suiyi-Light** [gnuf0rce/rss-helper#15]
反复推送
好像是不记录毫秒位导致的
![IMG_20220216_143127](https://user-images.githubusercontent.com/69178257/154209959-4107aa2a-a2e1-4135-a2f5-e3d521217d85.jpg)

rss-help版本：1.10
rss源：https://blog.x-lf.com/atom.xml

**Comment by cssxsh** [comment]
详尽到毫秒也是少见

**Comment by cssxsh** [comment]
with https://github.com/gnuf0rce/rss-helper/releases/tag/v1.1.1
