### ISSUE TITLE
解析youtube内容错误

### ISSUE THREAD

**Issue by Stars-OC** [gnuf0rce/rss-helper#22]
在解析youtube rss订阅的时候发生了feed.kt 83行npe问题
![6VOV$G439BC}%ELU%7F3Q9S](https://github.com/gnuf0rce/rss-helper/assets/41844884/489f524e-c5b4-43d6-8197-26e43854ae2d)

**Comment by cssxsh** [comment]
请给出具体的 rss 链接以供测试

**Comment by Stars-OC** [comment]
https://www.youtube.com/feeds/videos.xml?channel_id=UC2R4jVHzvUqR8WTjidaikpw
这是测试的
https://www.youtube.com/feeds/videos.xml?channel_id=UCeUJO1H3TEXu2syfAAPjYKQ
这是是正常链接 但是也不能进行推送
