### ISSUE TITLE
订阅Youtube 刷屏

### ISSUE THREAD

**Issue by Stars-OC** [gnuf0rce/rss-helper#23]
初始订阅Youtube时，会大量刷屏。希望能够做个限制，或者初始的订阅的时候将最新的进行添加
测试链接：https://rsshub.app/youtube/channel/UC6F7ZOpskuTyU2Mx73gUpsA
![image](https://github.com/gnuf0rce/rss-helper/assets/41844884/6c7a3e9e-761a-49ba-b18a-dffaee1f1d68)

**Comment by Stars-OC** [comment]
补充一下
![image](https://github.com/gnuf0rce/rss-helper/assets/41844884/a1df3fc9-7ab4-4ce7-b5ae-40e63d9e8adb)
![image](https://github.com/gnuf0rce/rss-helper/assets/41844884/fe2da93d-b434-4b6c-8316-5df4cf7072ac)
猜测应该是判断内容出错

**Comment by cssxsh** [comment]
初次订阅？

**Comment by Stars-OC** [comment]
是的

**Comment by cssxsh** [comment]
订阅的时候将最新的进行添加是有的，
前提是真的是第一次订阅

https://github.com/gnuf0rce/rss-helper/blob/d5b49094edc36e95fcb8891e4079abaed3a72dd4/src/main/kotlin/io/github/gnuf0rce/mirai/rss/RssSubscriber.kt#L121-L134

**Comment by Stars-OC** [comment]
会不会中途改了前缀的问题，之前因为是YouTube官方的rss，后面改成了rsshub的

**Comment by cssxsh** [comment]
自行查验 `SubscribeRecordData.yml`
如果真的是第一次订阅，`contact` 应该只有一个

**Comment by Stars-OC** [comment]
我再测试一下，看是否还有这种情况
麻烦你了

**Comment by Stars-OC** [comment]
修改SubscribeRecordData.yml的东西会导致此bug的产生，是我的问题
