### ISSUE TITLE
如何自定义订阅内容显示的字数

### ISSUE THREAD

**Issue by kuriyamasss** [gnuf0rce/rss-helper#9]
您好，目前通过订阅获取的内容会一次性显示所有内容，如何限制其在qq中显示的字数？

**Comment by cssxsh** [comment]
https://github.com/gnuf0rce/rss-helper/blob/master/readme.md#rsscontentconfig

**Comment by kuriyamasss** [comment]
> https://github.com/gnuf0rce/rss-helper/blob/master/readme.md#rsscontentconfig

感谢回复，但是这个limit的值是在RssContentConfig文件里修改吗？可我并没有在./config/rss-helper文件夹里找到此文件

**Comment by cssxsh** [comment]
好吧，我忘记载入这个配置了

**Comment by cssxsh** [comment]
> > https://github.com/gnuf0rce/rss-helper/blob/master/readme.md#rsscontentconfig
> 
> 感谢回复，但是这个limit的值是在RssContentConfig文件里修改吗？可我并没有在./config/rss-helper文件夹里找到此文件

1.0.4 修复

**Comment by kuriyamasss** [comment]
> > > https://github.com/gnuf0rce/rss-helper/blob/master/readme.md#rsscontentconfig
> > 
> > 
> > 感谢回复，但是这个limit的值是在RssContentConfig文件里修改吗？可我并没有在./config/rss-helper文件夹里找到此文件
> 
> 1.0.4 修复

十分感谢！
